Vagrant.configure("2") do |config|
  
  # First VM
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "Ubuntu"
    vm1.vm.provider "wsl2" do |wsl|
      wsl.distribution_name = "vagrant-net-vm1"
      wsl.version = 2
      wsl.systemd = true
      wsl.memory = 512
      wsl.cpus = 1
      wsl.hostname = "vagrant-net-vm1"
    end
    vm1.vm.network "private_network", ip: "192.168.50.10"
  end

  # Second VM
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "Debian"
    vm2.vm.provider "wsl2" do |wsl|
      wsl.distribution_name = "vagrant-net-vm2"
      wsl.version = 2
      wsl.systemd = true
      wsl.memory = 512
      wsl.cpus = 1
      wsl.hostname = "vagrant-net-vm2"
    end
    vm2.vm.network "private_network", ip: "192.168.50.11"
  end
end
