Vagrant.configure("2") do |config|
  config.vm.box = "Ubuntu-24.04"

  config.vm.provider "wsl2" do |wsl|
    wsl.distribution_name = "vagrant-wsl2-networking-demo"
    wsl.version = 2
    wsl.systemd = true
  end

  # Test private network with static IP
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "1.2.3.4"

  # Test port forwarding
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"

  # Start HTTP servers for testing
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update > /dev/null
    sudo apt install -y net-tools nginx > /dev/null
    
    netstat -lntp
  SHELL
end